keywords: 
  - "Data Scientist"
  - "Machine Learning"
  - "Robotics"
max_jobs: 2
description:
  positive:
    - "Python"
    - "C++"
    - "ROS"
    - "Machine Learning"
    - "AI"
  negative:
    - "Kafka"
    - "Excel"
    - "Sales"

location: "United States"
date_posted: "past_24_hours"  # Options: past_24_hours, past_week, past_month
easy_apply_only: true
verification: true  # Only verified companies
salary_range: "80000-120000"  # Example: 80k to 120k
job_type: 
  - "Full-time"
  - "Contract"
  - "Internship"
work_mode:
  - "Remote"
  - "Hybrid"
  - "Onsite"
experience_level:
  - "Entry level"
  - "Mid-Senior level"
blacklisted_companies:
  - "Jobot"
  - "Dice"
  