Python_Resume.pdf:
  - "Python"
  - "Machine Learning"
  - "AI"
  - "Data Science"

Robotics_Resume.pdf:
  - "Robotics"
  - "ROS"
  - "Path Planning"
  - "Automation"

Data_Science_Resume.pdf:
  - "TensorFlow"
  - "Keras"
  - "Pandas"
  - "Deep Learning"
  
applications: 3