login:
  username: "//input[@id='username']"
  password: "//input[@id='password']"
  submit: "//button[@type='submit']"

job_search:
  total_jobs: "//small"
  job_card: "//li[@data-occludable-job-id]"
  job_title: "//h1[contains(@class, 't-24 t-bold')]"
  company: "//div[contains(@class, 'job-details-jobs-unified-top-card__company-name')]//a"
  primary_description: "//div[contains(@class, 'job-details-jobs-unified-top-card__primary-description-container')]"
  show_more_button: "//button[contains(@class, 'feed-shared-inline-show-more-text__see-more-less-toggle')]"
  full_description: "//div[contains(@class, 'feed-shared-inline-show-more-text--expanded')]"


job_apply:
  easy_apply_button: "//button[contains(@aria-label, 'Easy Apply') and contains(@class, 'jobs-apply-button')]"
  question_text: "//div[contains(@class, 'jobs-easy-apply-form__question')]"
  answer_field: "//input[contains(@class, 'jobs-easy-apply-form__input')]"
  next_button: "//button[contains(text(), 'Next')]"
  upload_resume: "//input[@type='file']"
  submit_button: "//button[contains(text(), 'Submit application')]"