# User credentials for LinkedIn login
# Replace "_______@gmail.com" with your LinkedIn email address.
# Replace "-------------" with your LinkedIn password.

email: ___________@gmail.com   # Your LinkedIn email address.
password: ________    # Your LinkedIn password.
