# User credentials for LinkedIn login
# Replace "_______@gmail.com" with your LinkedIn email address.
# Replace "-------------" with your LinkedIn password.
credentials:
  email: _______@gmail.com   # Your LinkedIn email address.
  password: -------------    # Your LinkedIn password.
